# Generated by Django 2.0.7 on 2019-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0002_auto_20190218_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Adult', 'ADULT'), ('Adventure', 'ADVENTURE'), ('Animation', 'ANIMATION'), ('Biography', 'BIOGRAPHY'), ('Comedy', 'COMEDY'), ('Crime', 'CRIME'), ('Documentary', 'DOCUMENTARY'), ('Drama', 'DRAMA'), ('Family', 'FAMILY'), ('Fantasy', 'FANTASY'), ('Film', 'FILM'), ('Noir', 'NOIR'), ('Game - Show', 'GAMESHOW'), ('History', 'HISTORY'), ('Horror', 'HORROR'), ('Musical', 'MUSICAL'), ('Music', 'MUSIC'), ('Mystery', 'MYSTERY'), ('News', 'NEWS'), ('Reality - TV', 'REALITY'), ('Romance', 'ROMANCE'), ('Sci - Fi', 'SCIFI'), ('Short', 'SHORT'), ('Sport', 'SPORT'), ('Talk - Show', 'TALKSHOW'), ('Thriller', 'THRILLER'), ('War', 'WAR'), ('Western', 'WESTERN')], max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='special',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Trending'), (2, 'Featured')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.BooleanField(choices=[(False, 'User'), (True, 'Admin')], default=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='site',
            field=models.CharField(choices=[('Amazon', 'AMAZON'), ('Google Play', 'GOOGLE'), ('iTunes', 'ITUNES'), ('Netflix', 'NETFLIX')], max_length=15),
        ),
    ]
