# Generated by Django 2.1 on 2019-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0007_auto_20190218_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background',
            field=models.ImageField(upload_to='static/mobi/img'),
        ),
    ]
