# Generated by Django 2.1 on 2019-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0008_auto_20190223_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background',
            field=models.ImageField(upload_to='mobi/static/mobi/img'),
        ),
    ]
