# Generated by Django 2.1 on 2019-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0012_auto_20190223_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background',
            field=models.ImageField(upload_to='uploads/bg'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='uploads/poster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(null=True, upload_to='uploads/display_pic'),
        ),
    ]
