# Generated by Django 2.1 on 2019-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0015_auto_20190227_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(blank=True, to='mobi.Movie'),
        ),
    ]
