# Generated by Django 2.1 on 2019-03-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0016_auto_20190304_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.ImageField(null=True, upload_to='artist_pic/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='mobi.Genre'),
        ),
        migrations.AddField(
            model_name='cast',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobi.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, to='mobi.Cast'),
        ),
    ]
