# Generated by Django 2.1 on 2019-03-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0017_auto_20190304_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
