# Generated by Django 2.1 on 2019-03-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0018_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobi.User'),
        ),
    ]
