# Generated by Django 2.1 on 2019-03-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0019_auto_20190306_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobi.User'),
        ),
    ]
